version: "3"
services:
  spa-node:
    container_name: node-for-react

    build:
      context: .
      dockerfile: ./docker/node/Dockerfile

    env_file:
      ./.env

    tmpfs:
      - /run
      - /tmp

    deploy:
      mode: replicated
      replicas: 3

      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
        monitor: 120s

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

      resources:
        limits:
          cpus: "0.50"
          memory: 500M

        reservations:
          cpus: "0.25"
          memory: 200M

    ports:
      - "3000:3000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3

    logging:
      driver: json-file

      options:
        max-size: "200k"
        max-file: "10"

    restart: always
