export const submitBtnTitle = 'Submit';
export const BackBtnTitle = 'Back';
export const AddToCartBtnTitle = 'Add to cart';
export const AddToWishlistBtnTitle = 'Add to Wishlist';
export const RemoveBtnTitle = 'Remove';
export const LogOutBtnTitle = 'Log Out';
export const LogInBtnTitle = 'Log In';
export const RegisterBtnTitle = 'Register';
export const ContinueCheckoutTitle = 'Continue to checkout';
