export const ADDRESSES_LIST = 'ADDRESSES_LIST';

export const ADD_ADDRESS = 'ADD_ADDRESS';

export const DELETE_ADDRESS = 'DELETE_ADDRESS';

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';

export const SET_CURRENT_ADDRESS = 'SET_CURRENT_ADDRESS';
