export const CUSTOMER_DATA_REQUEST = 'CUSTOMER_DATA_REQUEST';
export const CUSTOMER_DATA_UPDATE = 'CUSTOMER_DATA_UPDATE';
export const LOGIN_DATA_SET_TO_STORE = 'LOGIN_DATA_SET_TO_STORE';
export const CUSTOMER_PASSWORD_UPDATE = 'CUSTOMER_PASSWORD_UPDATE';
export const CUSTOMER_DELETE_ENTITY = 'CUSTOMER_DELETE_ENTITY';
