export const PAGES_LOGIN_REQUEST = 'PAGES_LOGIN_REQUEST';

export const PAGES_CUSTOMER_REGISTER = 'PAGES_CUSTOMER_REGISTER';

export const PAGES_CUSTOMER_LOGOUT = 'PAGES_CUSTOMER_LOGOUT';

export const REFRESH_TOKEN_REQUEST = 'PAGES_LOGIN_REQUEST';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

export const RESET_PASSWORD = 'RESET_PASSWORD';
