export const PAGES_SEARCH_REQUEST = 'PAGES_SEARCH_REQUEST';

export const PAGES_SEARCH_REQUEST_CLEAR = 'PAGES_SEARCH_REQUEST_CLEAR';
export const PAGES_SEARCH_TERM_CLEAR = 'PAGES_SEARCH_TERM_CLEAR';

export const PAGES_SUGGESTION_REQUEST = 'PAGES_SUGGESTION_REQUEST';
