export const WISHLIST_ALL_LISTS = 'WISHLIST_ALL_LISTS';

export const ADD_WISHLIST = 'ADD_WISHLIST';

export const DETAIL_WISHLIST = 'DETAIL_WISHLIST';

export const DELETE_WISHLIST = 'DELETE_WISHLIST';

export const UPDATE_WISHLIST = 'UPDATE_WISHLIST';

export const ADD_ITEM_WISHLIST = 'ADD_ITEM_WISHLIST';

export const DELETE_ITEM_WISHLIST = 'DELETE_ITEM_WISHLIST';
